### PR TITLE
Add method to add words to dictionary

### PR DESCRIPTION
**Pull request by skewart**
Towards #5

### CODE REVIEW

**Comment by wearhere** [comment]
This looks great, the only two things are:

- [] Can you add a little bit to the README about this?
- [] Do you need to [set a custom dictionary](https://github.com/atom/node-spellchecker/blob/master/lib/spellchecker.js#L20) to use this? I'm confused by [this](https://github.com/atom/node-spellchecker#spellcheckeraddword) saying "Use a custom dictionary file."

**Comment by skewart** [comment]
I've been on vacation and I'm just seeing this.  I'd be happy to add something to the README.  I'm not entirely sure if you ever need to manage a custom dictionary file in the context of an Electron app. Simply calling `add` - like in this PR - has worked just fine with both Mac and Windows builds (running on Windows 10).  Words added to the dictionary were persisted across multiple restarts, and appeared added to the dictionary from Chrome as well.   Granted, those builds didn't use the very latest version of Electron, and I haven't looked in to how it would work when built against older versions either.

I'll spend some time digging in to the custom dictionary file a bit more.

**Comment by skewart** [comment]
I tested this on the latest version of Electron and things work fine.   Let me know if the addition to the README sounds good.  I'm happy to change it if you think it could be better.

**Comment by wearhere** [comment]
Thanks @skewart! Can you note in the README that additions are persistent? Otherwise lgtm.

**Comment by skewart** [comment]
Awesome. I just updated the README to mention that additions are persistent.

**Comment by wearhere** [comment]
Thanks! Published v1.1.0.

**Comment by skewart** [comment]
No problem!

**Pull request merged**
